Add CI/CD

diff --git a/.gitea/workflows/build.yml b/.gitea/workflows/build.yml
--- a/.gitea/workflows/build.yml
+++ b/.gitea/workflows/build.yml
@@ -22,7 +22,21 @@ jobs:
         run: chmod +x ./gradlew
 
       - name: Verify AAR File Integrity
-        run: unzip -t app/libs/firefly-go.aar || (echo "AAR file is corrupted! Fix it in the repo." && exit 1)
+        run: |
+          FILE="app/libs/firefly-go.aar"
+          if [ ! -f "$FILE" ]; then
+          echo "❌ File not found: $FILE"
+          exit 1
+          fi
+          
+          echo "📄 File info:"
+          ls -lh "$FILE"
+          
+          echo "🖇 Check AAR content:"
+          unzip -l "$FILE" || (echo "❌ AAR file is corrupted! Fix it in the repo." && exit 1)
+          
+          echo "✅ AAR file seems OK"
+
 
       - name: Clean Gradle
         run: ./gradlew clean
